# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/175PonR7Nc8EVaVO7AdmE3Fnu5S9OSq7r
"""

# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/175PonR7Nc8EVaVO7AdmE3Fnu5S9OSq7r
"""

# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/175PonR7Nc8EVaVO7AdmE3Fnu5S9OSq7r
"""

# -*- coding: utf-8 -*-
"""
SPUS Quantitative Analyzer v11 (Fibonacci Model)

This script performs a multi-factor quantitative analysis (Value, Momentum, Quality, Size)
on SPUS holdings. It now calculates dynamic Fibonacci retracement (61.8%)
and extension (161.8%) levels based on the recent 90-day high/low.
"""

import requests
import yfinance as yf
import pandas as pd
import pandas_ta as ta
import time
import os
import logging
from datetime import datetime, timedelta
from concurrent.futures import ThreadPoolExecutor, as_completed, TimeoutError
import openpyxl
from openpyxl.styles import Font
import io
import json
import requests.exceptions


# --- Function to load external config file ---
def load_config(path='config.json'):
    try:
        with open(path, 'r') as f:
            config = json.load(f)
        logging.info(f"Successfully loaded configuration from {path}")
        return config
    except FileNotFoundError:
        logging.error(f"FATAL: Configuration file '{path}' not found.")
        return None
    except json.JSONDecodeError:
        logging.error(f"FATAL: Could not decode JSON from '{path}'. Check for syntax errors.")
        return None
# ---------------------------------------------

# ⭐️ --- CRITICAL FIX: Load CONFIG at module level --- ⭐️
# This makes the CONFIG variable available to all functions when imported.
CONFIG = load_config('config.json')
# ----------------------------------------------------


# --- CONFIGURATION BLOCK ---
# CONFIG block removed, loaded from config.json
# --------------------------------

# --- NEW ROBUST FETCHER FUNCTION ---
def fetch_spus_tickers():
    '''
    Fetches SPUS holdings tickers by reading a local CSV file.
    This version reads from a predefined local path.
    '''
    # url = 'https://www.sp-funds.com/wp-content/uploads/data/TidalFG_Holdings_SPUS.csv' # Original URL commented out

    # Check if CONFIG was loaded successfully
    if CONFIG is None:
        logging.error("fetch_spus_tickers: CONFIG is None. Cannot find CSV path.")
        return []

    local_path = CONFIG['SPUS_HOLDINGS_CSV_PATH']
    ticker_column_name = 'StockTicker' # Correct column name

    if not os.path.exists(local_path):
        logging.error(f"Local SPUS holdings file not found at: {local_path}")
        return []

    try:
        # Try to let pandas handle the parsing directly
        holdings_df = pd.read_csv(local_path)

    except pd.errors.ParserError:
        # If default parsing fails, it's likely due to metadata at the top.
        # Let's try skipping the first few lines.
        logging.warning("Pandas ParserError. Trying again with 'skiprows'...")
        for i in range(1, 10): # Try skipping up to 9 lines
            try:
                holdings_df = pd.read_csv(local_path, skiprows=i)
                if ticker_column_name in holdings_df.columns:
                    logging.info(f"Successfully parsed CSV by skipping {i} rows.")
                    break # Found the header
            except Exception:
                continue # Try next skip value
        else:
            # This 'else' belongs to the 'for' loop
            logging.error(f"Failed to parse CSV from {local_path} even after skipping 9 rows.")
            return []

    except Exception as e:
        logging.error(f"An unexpected error occurred during local CSV read/parse: {e}")
        return []

    # --- Post-processing: Clean the DataFrame ---

    if ticker_column_name not in holdings_df.columns:
        logging.error(f"CSV from {local_path} downloaded, but '{ticker_column_name}' column not found.")
        return []

    # Clean metadata from the *bottom* of the file (e.g., "Total" rows)
    # These often appear as NaN in the 'StockTicker' column.
    try:
        # Ensure 'StockTicker' column is string type before checking for NaN
        holdings_df[ticker_column_name] = holdings_df[ticker_column_name].astype(str)
        first_nan_index = holdings_df[holdings_df[ticker_column_name].isna()].index[0]
        holdings_df = holdings_df.iloc[:first_nan_index]
        logging.info("Removed footer metadata from CSV.")
    except IndexError:
        # No NaN rows found, assume file is clean
        pass
    except Exception as e:
         logging.warning(f"Error cleaning footer metadata: {e}")
         pass # Continue even if cleaning fails


    ticker_symbols = holdings_df[ticker_column_name].tolist()

    # Final cleaning of the list
    ticker_symbols = [s for s in ticker_symbols if isinstance(s, str) and s and s != ticker_column_name and 'CASH' not in s]

    logging.info(f"Successfully fetched {len(ticker_symbols)} ticker symbols for SPUS from local file.")
    return ticker_symbols
# --- END NEW FUNCTION ---


# 2. Define helper functions

# --- ⭐️ UPDATED Support/Resistance Function to include Dates and Fib Levels ---
def calculate_support_resistance(hist_df):
    """
    Calculates Support, Resistance, Dates, and Fibonacci levels
    based on the lookback period.
    """
    if hist_df is None or hist_df.empty:
        return None, None, None, None, None, None

    try:
        lookback_period = CONFIG.get('SR_LOOKBACK_PERIOD', 90)

        if len(hist_df) < lookback_period:
            recent_hist = hist_df
        else:
            recent_hist = hist_df.iloc[-lookback_period:]

        # Find Support (min low) and its date
        support_val = recent_hist['Low'].min()
        support_date = recent_hist['Low'].idxmin()

        # Find Resistance (max high) and its date
        resistance_val = recent_hist['High'].max()
        resistance_date = recent_hist['High'].idxmax()

        # Calculate Fibonacci Levels
        fib_61_8_level = None
        fib_161_8_level = None

        high_low_diff = resistance_val - support_val
        if high_low_diff > 0:
            # Fib 61.8% Retracement (Support Level)
            fib_61_8_level = resistance_val - (high_low_diff * 0.618)

            # Fib 161.8% Extension (Profit Target)
            fib_161_8_level = resistance_val + (high_low_diff * 0.618)

        return support_val, support_date, resistance_val, resistance_date, fib_61_8_level, fib_161_8_level

    except Exception as e:
        logging.warning(f"Error in calculate_support_resistance: {e}. Defaulting to long-term S/R.")
        # Fallback to the old method in case of error
        support_val = hist_df['Low'].min()
        support_date = hist_df['Low'].idxmin()
        resistance_val = hist_df['High'].max()
        resistance_date = hist_df['High'].idxmax()
        return support_val, support_date, resistance_val, resistance_date, None, None
# --- ⭐️ END UPDATED Function ---


def calculate_financials_and_fair_price(ticker_obj, last_price, ticker):
    """
    Calculates financials. NOW checks for a cached .json file
    for the `.info` data before making a network request.
    """
    info = {}
    cache_path = os.path.join(CONFIG['INFO_CACHE_DIR'], f"{ticker}.json")
    cache_duration_seconds = CONFIG['INFO_CACHE_DURATION_HOURS'] * 3600

    try:
        # Check if a fresh cache file exists
        if os.path.exists(cache_path) and (time.time() - os.path.getmtime(cache_path) < cache_duration_seconds):
            with open(cache_path, 'r') as f:
                info = json.load(f)
            logging.info(f"[{ticker}] Loaded fundamental data from cache.")
        else:
            # If no cache or cache is stale, fetch from network
            logging.info(f"[{ticker}] Fetching fundamental data from network...")
            info = ticker_obj.info
            # Save the new data to cache
            with open(cache_path, 'w') as f:
                json.dump(info, f, indent=4)

        # --- Now, proceed with the 'info' dictionary ---
        pe_ratio = info.get('forwardPE', None)
        pb_ratio = info.get('priceToBook', None)
        div_yield = info.get('dividendYield', None)
        debt_to_equity = info.get('debtToEquity', None)
        rev_growth = info.get('revenueGrowth', None)
        roe = info.get('returnOnEquity', None)
        ev_ebitda = info.get('enterpriseToEbitda', None)
        ps_ratio = info.get('priceToSalesTrailing12Months', None)
        high_52wk = info.get('fiftyTwoWeekHigh', None)
        low_52wk = info.get('fiftyTwoWeekLow', None)
        market_cap = info.get('marketCap', None)
        sector = info.get('sector', 'N/A') # --- ADDED SECTOR ---

        eps = info.get('trailingEps', None)
        bvps = None
        graham_number = None
        valuation_signal = "N/A"

        if eps is not None and pb_ratio is not None and eps > 0 and pb_ratio > 0 and last_price is not None:
            bvps = last_price / pb_ratio
            graham_number = (22.5 * eps * bvps) ** 0.5

            if last_price < graham_number:
                valuation_signal = "Undervalued (Graham)"
            else:
                valuation_signal = "Overvalued (Graham)"
        elif eps is not None and eps <= 0:
            valuation_signal = "Unprofitable (EPS < 0)"

        financial_dict = {
            'Forward P/E': pe_ratio,
            'P/B Ratio': pb_ratio,
            'Market Cap': market_cap,
            'Sector': sector, # --- ADDED SECTOR ---
            'Dividend Yield': div_yield * 100 if div_yield else None,
            'Debt/Equity': debt_to_equity,
            'Revenue Growth (QoQ)': rev_growth * 100 if rev_growth else None,
            'Return on Equity (ROE)': roe * 100 if roe else None,
            'EV/EBITDA': ev_ebitda,
            'Price/Sales (P/S)': ps_ratio,
            '52 Week High': high_52wk,
            '52 Week Low': low_52wk,
            'Graham Number': graham_number,
            'Valuation (Graham)': valuation_signal
        }
        return financial_dict

    except Exception as e:
        logging.error(f"Error fetching/processing fundamental data for {ticker}: {e}")
        # Return all keys as None
        # --- ADDED SECTOR TO NULL DICT ---
        return {key: None for key in ['Forward P/E', 'P/B Ratio', 'Market Cap', 'Sector', 'Dividend Yield', 'Debt/Equity', 'Revenue Growth (QoQ)', 'Graham Number', 'Valuation (Graham)', 'Return on Equity (ROE)', 'EV/EBITDA', 'Price/Sales (P/S)', '52 Week High', '52 Week Low']}
# --- ⭐️ END UPDATED FUNCTION 1 ---


# Old calculate_quant_score function removed (replaced by Z-Score ranking).

# 3. Dedicated function for data fetching
# --- ⭐️ UPDATED FUNCTION 2: ADDED NEWS & CALENDAR + BUG FIX ---
def process_ticker(ticker):
    """
    Processes a single ticker. Fetches history (cached),
    fundamentals (cached), and live news/calendar.
    """

    null_return = {
        'ticker': ticker, 'momentum': None, 'rsi': None, 'last_price': None,
        'support_resistance': None, 'trend': None, 'macd': None, 'signal_line': None,
        'hist_val': None, 'macd_signal': None, 'financial_dict': None, 'success': False,
        'recent_news': "N/A", 'latest_headline': "N/A", 'earnings_date': "N/A" # --- ADDED ---
    }

    # Check if CONFIG was loaded successfully
    if CONFIG is None:
        logging.error(f"process_ticker ({ticker}): CONFIG is None. Cannot find cache paths.")
        return null_return

    file_path = os.path.join(CONFIG['HISTORICAL_DATA_DIR'], f'{ticker}.feather')
    existing_hist_df = pd.DataFrame()
    start_date = None

    if os.path.exists(file_path):
        try:
            existing_hist_df = pd.read_feather(file_path)
            existing_hist_df['Date'] = pd.to_datetime(existing_hist_df['Date'])
            existing_hist_df.set_index('Date', inplace=True)

            if not existing_hist_df.empty:
                existing_hist_df.index = pd.to_datetime(existing_hist_df.index, utc=True)
                last_date = existing_hist_df.index.max()
                start_date = last_date + timedelta(days=1)
        except Exception as e:
            logging.warning(f"Error loading existing FEATHER data for {ticker}: {e}")
            existing_hist_df = pd.DataFrame()

    new_hist = pd.DataFrame()
    ticker_obj = None
    fetch_success = False

    # --- ⭐️ FIX: Check if cache is already up-to-date ---
    today = datetime.now().date()
    should_fetch = True
    if start_date:
        # If the calculated start_date is *after* today, don't fetch
        if start_date.date() > today:
            logging.info(f"[{ticker}] History cache is already up-to-date (Last: {start_date.date() - timedelta(days=1)}). Skipping network fetch.")
            should_fetch = False

    if should_fetch:
        for attempt in range(3):
            try:
                ticker_obj = yf.Ticker(ticker)
                if start_date:
                    # Fetch from start_date (which is in the past or today)
                    new_hist = ticker_obj.history(start=start_date.strftime('%Y-%m-%d'))
                else:
                    # Fetch full history
                    new_hist = ticker_obj.history(period=CONFIG['HISTORICAL_DATA_PERIOD'])
                fetch_success = True
                break
            except (requests.exceptions.ConnectionError, requests.exceptions.ReadTimeout, TimeoutError) as e:
                logging.warning(f"[{ticker}] Network error on attempt {attempt+1}/3: {e}. Retrying in {5*(attempt+1)}s...")
                time.sleep(5 * (attempt+1))
            except Exception as e:
                # This catches the yfinance "start date after end date" error if it still occurs
                logging.error(f"Error fetching new history for {ticker}: {e}")
                break
    # --- ⭐️ END FIX ---

    if not fetch_success and existing_hist_df.empty:
        logging.error(f"[{ticker}] Failed to fetch history and no cache exists.")
        return null_return

    # --- ⭐️ FIX 2: Handle concat warning ---
    # Only concat if new_hist actually has data.
    if not new_hist.empty:
        combined_hist = pd.concat([existing_hist_df, new_hist]).drop_duplicates(keep='last').sort_index()
    else:
        combined_hist = existing_hist_df
    # --- ⭐️ END FIX 2 ---

    if combined_hist.empty:
        # This can happen if the ticker is delisted (e.g., AOS) and we have no cache
        logging.warning(f"[{ticker}] No history data found (possibly delisted).")
        return null_return

    if not combined_hist.index.is_unique:
         duplicate_dates = combined_hist.index[combined_hist.index.duplicated(keep='first')]
         logging.warning(f"Removed duplicate dates for {ticker} before calculating TA: {duplicate_dates.tolist()}")
         combined_hist = combined_hist[~combined_hist.index.duplicated(keep='first')]

    hist = combined_hist

    momentum = None
    rsi = None
    last_price = None
    support_resistance = None
    trend = 'Insufficient data for trend'

    try:
        hist.ta.rsi(length=CONFIG['RSI_WINDOW'], append=True)
        hist.ta.sma(length=CONFIG['SHORT_MA_WINDOW'], append=True)
        hist.ta.sma(length=CONFIG['LONG_MA_WINDOW'], append=True)
        hist.ta.macd(fast=CONFIG['MACD_SHORT_SPAN'], slow=CONFIG['MACD_LONG_SPAN'], signal=CONFIG['MACD_SIGNAL_SPAN'], append=True)
    except Exception as e:
        logging.warning(f"Error calculating TA for {ticker}: {e}. Skipping TA.")
        pass

    rsi_col = f'RSI_{CONFIG["RSI_WINDOW"]}'
    short_ma_col = f'SMA_{CONFIG["SHORT_MA_WINDOW"]}'
    long_ma_col = f'SMA_{CONFIG["LONG_MA_WINDOW"]}'
    macd_col = f'MACD_{CONFIG["MACD_SHORT_SPAN"]}_{CONFIG["MACD_LONG_SPAN"]}_{CONFIG["MACD_SIGNAL_SPAN"]}'
    macd_h_col = f'MACDh_{CONFIG["MACD_SHORT_SPAN"]}_{CONFIG["MACD_LONG_SPAN"]}_{CONFIG["MACD_SIGNAL_SPAN"]}'
    macd_s_col = f'MACDs_{CONFIG["MACD_SHORT_SPAN"]}_{CONFIG["MACD_LONG_SPAN"]}_{CONFIG["MACD_SIGNAL_SPAN"]}'

    if not hist.empty:
        last_price = hist['Close'].iloc[-1]

        min_data_points = CONFIG['MIN_DATA_POINTS_MOMENTUM']
        if len(hist) >= min_data_points:
            try:
                price_now = hist['Close'].iloc[-1]
                # --- ⭐️ SYNTAX FIX IS HERE ---
                price_year_ago = hist['Close'].iloc[-min_data_points]
                # --- ⭐️ END FIX ---
                momentum = ((price_now - price_year_ago) / price_year_ago) * 100
            except IndexError:
                pass

        rsi = hist[rsi_col].iloc[-1] if rsi_col in hist.columns else None
        last_short_ma = hist[short_ma_col].iloc[-1] if short_ma_col in hist.columns else None
        last_long_ma = hist[long_ma_col].iloc[-1] if long_ma_col in hist.columns else None

        macd = hist[macd_col].iloc[-1] if macd_col in hist.columns else None
        hist_val = hist[macd_h_col].iloc[-1] if macd_h_col in hist.columns else None
        signal_line = hist[macd_s_col].iloc[-1] if macd_s_col in hist.columns else None

        trend = 'No Clear Trend'
        if not pd.isna(last_short_ma) and not pd.isna(last_long_ma) and not pd.isna(last_price):
            if last_short_ma > last_long_ma:
                if last_price > last_short_ma:
                    trend = 'Confirmed Uptrend'
                else:
                    trend = 'Uptrend (Correction)'
            elif last_short_ma < last_long_ma:
                if last_price < last_short_ma:
                    trend = 'Confirmed Downtrend'
                else:
                    trend = 'Downtrend (Rebound)'

        macd_signal = "N/A"
        if macd_h_col in hist.columns and len(hist) >= 2 and not pd.isna(hist_val):
            prev_hist = hist[macd_h_col].iloc[-2]
            if not pd.isna(prev_hist):
                if hist_val > 0 and prev_hist <= 0:
                    macd_signal = "Bullish Crossover (Favorable)"
                elif hist_val < 0 and prev_hist >= 0:
                    macd_signal = "Bearish Crossover (Unfavorable)"
                elif hist_val > 0:
                    macd_signal = "Bullish (Favorable)"
                elif hist_val < 0:
                    macd_signal = "Bearish (Unfavorable)"

        # --- ⭐️ MODIFIED S/R CALL ---
        support, support_date, resistance, resistance_date, fib_61_8, fib_161_8 = calculate_support_resistance(hist)

        # Format dates
        support_date_str = support_date.strftime('%Y-%m-%d') if pd.notna(support_date) else "N/A"
        resistance_date_str = resistance_date.strftime('%Y-%m-%d') if pd.notna(resistance_date) else "N/A"

        if support is not None and resistance is not None:
            support_resistance = {
                'Support': support,
                'Support_Date': support_date_str,
                'Resistance': resistance,
                'Resistance_Date': resistance_date_str,
                'Fib_61_8': fib_61_8,
                'Fib_161_8': fib_161_8
            }
        # --- ⭐️ END MODIFICATION ---


        # We need a ticker_obj to get financials. If we skipped fetch, create it.
        if ticker_obj is None:
            ticker_obj = yf.Ticker(ticker)

        financial_dict = calculate_financials_and_fair_price(ticker_obj, last_price, ticker)

        # --- ⭐️ NEW: Fetch News and Calendar Events ---
        recent_news_flag = "No"
        latest_headline = "N/A"
        earnings_date = "N/A"
        try:
            # Fetch news
            news = ticker_obj.news
            if news:
                latest_headline = news[0].get('title', "N/A")
                now_ts = datetime.now().timestamp()
                # 48 hours = 172800 seconds
                forty_eight_hours_ago_ts = now_ts - 172800

                for item in news:
                    if item.get('providerPublishTime', 0) > forty_eight_hours_ago_ts:
                        recent_news_flag = "Yes"
                        break # Found one, no need to keep checking

            # Fetch calendar
            calendar = ticker_obj.calendar
            # --- ⭐️ BUG FIX: Check if calendar is a non-empty dictionary ---
            if calendar and isinstance(calendar, dict) and 'Earnings Date' in calendar and calendar['Earnings Date']:
                # Get the first date from the list
                date_val = calendar['Earnings Date'][0]

                # Now format the date
                if isinstance(date_val, str):
                    earnings_date = date_val
                elif hasattr(date_val, 'strftime'): # Handle timestamp
                    earnings_date = date_val.strftime('%Y-%m-%d')
                else:
                    earnings_date = str(date_val)
            # --- ⭐️ END BUG FIX ---

        except Exception as e:
            logging.warning(f"[{ticker}] Error fetching news or calendar: {e}")
        # --- ⭐️ END NEW BLOCK ---


        try:
            # Only write to cache if we actually fetched new data
            if not new_hist.empty:
                combined_hist.reset_index().to_feather(file_path)
        except Exception as e:
            logging.error(f"[{ticker}] Failed to save Feather cache: {e}")

        return {
            'ticker': ticker,
            'momentum': momentum,
            'rsi': rsi,
            'last_price': last_price,
            'support_resistance': support_resistance,
            'trend': trend,
            'macd': macd,
            'signal_line': signal_line,
            'hist_val': hist_val,
            'macd_signal': macd_signal,
            'financial_dict': financial_dict,
            'recent_news': recent_news_flag,      # --- ADDED ---
            'latest_headline': latest_headline,  # --- ADDED ---
            'earnings_date': earnings_date,        # --- ADDED ---
            'success': True
        }

    return null_return
# --- ⭐️ END UPDATED FUNCTION 2 ---


# ⭐️ --- CRITICAL FIX: --- ⭐️
# The entire 'if __name__ == "__main__":' block (from line 632 to 1139)
# has been REMOVED.
#
# REASON:
# All of this logic is now correctly placed inside the
# 'run_full_analysis' function within streamlit_app.py.
# Keeping it here would cause it to run *in addition* to the Streamlit app
# and cause errors. This file (spus.py) is now purely a library.
# ⭐️ --------------------- ⭐️